// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceConsumer.Data;

namespace ServiceConsumer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220131153925_FixFK")]
    partial class FixFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceConsumer.Models.Organization", b =>
                {
                    b.Property<Guid>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            OrganizationID = new Guid("b35a3c95-b96e-4bd0-9a54-86f282ed9543"),
                            Name = "Marvel"
                        },
                        new
                        {
                            OrganizationID = new Guid("1fecb8bf-bf38-41e7-8146-00ad585c2e18"),
                            Name = "Universal"
                        });
                });

            modelBuilder.Entity("ServiceConsumer.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OrganizationID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("d30fbdc8-e4e7-4f0a-a95e-8ff01d403872"),
                            Email = "abc@gmail.kz",
                            LastName = "Hohland",
                            MiddleName = "Ivanovich",
                            Name = "Tom"
                        },
                        new
                        {
                            UserID = new Guid("dd2675c9-3119-4b7f-9aba-34a128b5d4b7"),
                            Email = "WolfAlice@outllok.com",
                            LastName = "Wolf",
                            Name = "Alice"
                        });
                });

            modelBuilder.Entity("ServiceConsumer.Models.User", b =>
                {
                    b.HasOne("ServiceConsumer.Models.Organization", null)
                        .WithMany("Users")
                        .HasForeignKey("OrganizationID");
                });

            modelBuilder.Entity("ServiceConsumer.Models.Organization", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
